### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by egoist** [diegorodriguesvieira/vue-final-form#1]
Hi,

I noticed that you own `vue-final-form` on npm, are you going to use it? I also made one but named `vue-finalform` 😕, feel free to close this if you have plan for this project 😅

**Comment by diegorodriguesvieira** [comment]
Hello @egoist
Currently I have no time available to start the project development...then in favor of the community I will pass the package name to you...

Thanks

**Comment by egoist** [comment]
Oh thanks, it's very nice of you 😄

My npm username is `rem`, I will republish https://github.com/egoist/vue-finalform then

**Comment by diegorodriguesvieira** [comment]
@egoist  Do I have to delete the package and you create it again?

**Comment by egoist** [comment]
nope you can never delete packages on npm now 😄 simply run `npm owner add rem vue-final-form`

**Comment by xbrain-admin** [comment]
Nice! I did! 😄

**Comment by diegorodriguesvieira** [comment]
Nice! I did! 😄

**Comment by egoist** [comment]
Thanks, published. 🎉
